---
- name: enable yum repo # failed, so we try to install epel 7.8
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
    state: present

- name: install python-pip # CentOS also do have pip, so we install python-pip
  yum:
    name: python-pip
    state: latest

- name: upgrade pip  # we also need to upgrade pip itself
  pip:
    name: pip
    extra_args: --upgrade
    state: latest

- name: create system account
  user:
    name: "{{ system_account }}"
    shell: /bin/bash
    state: present
    comment: This is an ansbile managed account
  tags:
    - provision-system-account

- name: provide sudo power
  copy:
    content: |
      %{{ system_account }} ALL=(ALL) NOPASSWD: ALL
    dest: /etc/sudoers.d/{{ system_account }}
  when: "{{ enable_sudoer }}"

- name: disable requiretty for a system account {{ system_account }}
  copy:
    content: |
      Defaults:{{ system_account }} !requiretty
    dest: /etc/sudoers.d/999-disable-requiretty
    mode: 0440
  when: "{{ disable_requiretty }}"
  vars:
    ansible_ssh_pipelining: no
  tags:
    - disable-requiretty

- name: create .aws directory
  file:
    path: /home/{{ system_account }}/.aws
    state: directory
  become: yes
  become_user: "{{ system_account }}"
  tags:
    - provision-system-account

- name: generate aws credentials
  copy:
    content: |
      [default]
      AWS_ACCESS_KEY_ID={{ aws_key_id }}
      AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}
    dest: /home/{{ system_account }}/.aws/credentials
    mode: "0600"
  become: yes
  become_user: "{{ system_account }}"
  tags:
    - provision-system-account
    - provision-awscli-config

- name: generate aws config
  copy:
    content: |
      [default]
      output = json
    dest: /home/{{ system_account }}/.aws/config
    mode: "0600"
  become: yes
  become_user: "{{ system_account }}"
  tags:
    - provision-system-account
    - provision-awscli-config

- name: install awscli
  pip:
    name: awscli
    state: present
  tags:
    - provision-system-account
    - install-python-awscli
