---
- name: enable yum repo # failed, so we try to install epel 7.8
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
    state: present
  when: "{{ deploy_aws_cred }}"

- name: install python-pip # CentOS also do have pip, so we install python-pip
  yum:
    name: python-pip
    state: latest
  become: yes

- name: upgrade pip  # we also need to upgrade pip itself
  pip:
    name: pip
    extra_args: --upgrade
    state: latest
  become: yes
